# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a43c42038b51dc068fe06f198f109be503b857e1a603a0f93923836b6db0dacfd28a97eeec7e617fd648b09406ec476030df8a1415782514d419a90f200b75d

test:
  secret_key_base: f920472abf2065bc8a7fcdecc3d10dbe365a8081cbda7edea2ee7bdabbd88e9715166d181da03e2c36a1dc92e456d8e179b73c6cd3e622029950b118e6e020fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
